name: fashion_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ğŸ”‘ State management (MVVM iÃ§in)
  provider: ^6.1.2

  # ğŸ“¸ GÃ¶rsel seÃ§mek iÃ§in
  image_picker: ^1.1.1

  # ğŸ”‘ Fal client (en gÃ¼ncel pub.dev sÃ¼rÃ¼mÃ¼)
  fal_client: ^0.3.0

  # ğŸ“‚ fal.storage.upload iÃ§in dosya tipi desteÄŸi
  cross_file: ^0.3.4+2

  # ğŸ”‘ Ortam deÄŸiÅŸkenleri (.env) iÃ§in
  flutter_dotenv: ^5.1.0

  # ğŸŒ Proxy API veya ekstra HTTP istekleri iÃ§in
  http: ^1.2.2

  # ğŸ”§ Ek koleksiyon yardÄ±mcÄ±larÄ±
  collection: ^1.18.0

  google_fonts: ^6.2.1
  lottie: ^3.1.2
  smooth_page_indicator: ^1.1.0
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3

    # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.0
  
  # Google sign-in
  google_sign_in: ^6.2.1

  in_app_purchase: ^3.1.11

  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/hero.png
    - assets/step1.png
    - assets/step2.png
    - assets/step3.png
    - assets/trust.png
    - assets/tryon.json
    - assets/google.png
    - assets/processing.json
